// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tfevhpnbcuhtqnfleyuw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRmZXZocG5iY3VodHFuZmxleXV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4Mjk1OTEsImV4cCI6MjA3NDQwNTU5MX0.sFoA4zN9grXhlfIGfyLBl75J_5Fmc9DT4fNC5uvkGwA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});